### ISSUE TITLE
Is there any R package to OMIM, Orphanet and Decipher data analysis?

### ISSUE THREAD

**Issue by Shicheng-Guo** [orphanet-rare-diseases-issues/RD-CODE#6]
Is there any R package to integrate OMIM, Orphanet and Decipher data analysis?

**Comment by JTorphanet** [comment]
Dear @Shicheng-Guo, 

Sorry for this late reply. Orphanet does not propose a R package to cross-analyze due to the huge number and diversity of requests. However, thanks to the different Orphanet tools available (Nomenclature pack, Orphadata, DataViz) you can generate different data analysis in your own way. 

In the meantime, I invite you to join the new GitHub [OD4RD GitHub] (https://github.com/OD4RD) if you have more questions!

Best, 

Julie
