### ISSUE TITLE
ORPHA:157215  Hereditary hypophosphatemic rickets with hypercalciuria

### ISSUE THREAD

**Issue by Marlies99** [orphanet-rare-diseases-issues/RD-CODE#7]
Hi
I am wondering if the Orphacode "ORPHA:157215  Hereditary hypophosphatemic rickets with hypercalciuria" is only for homozygous and compound heterozygous mutations in the SLC34A3 gene?
Is it non rare if the patient has a heterozygous mutation in the SLC34A3 gene? The patient has mild symptoms: mild hypophosphatemia, mild hypercalciuria with the heterozygous mutation.

In Orphanet is written:
**Etiology**
HHRH is caused by homozygous or compound heterozygous mutations in the SLC34A3 gene encoding a sodium-dependent phosphate transporter (NaPi-IIc/NPT2c).

Thanks for the feedback.
Best Regards
Marlies

**Comment by houda-ali** [comment]
Dear Marlies,
Our gene database manager has reviewed the entity, and it appeared that patients with heterozygous mutations in SLC34A3 have also been described, as well as cases with causative mutations in another gene, SLC34A1 (see [PMID: 32311027](https://pubmed-ncbi-nlm-nih-gov.proxy.insermbiblio.inist.fr/32311027/)).
Therefore, the entity ORPHA:157215 "Hereditary hypophosphatemic rickets with hypercalciuria" is now associated with both SLC34A3 and SLC34A1, and the Autosomal dominant and Autosomal recessive inheritances.
You can already see these updates on the Orphanet website, and the text will be updated with experts as the information is outdated, however the person in charge of this activity is currently on maternity leave so this will have to wait for her return.
Thank you, and I hope this helps,
Kind regards,
Houda

**Comment by MCecile-US14** [comment]
Dear @Marlies99, 
Very sorry for the late reply, Houda left the team in spring 2022, I am the Nomenclature manager in charge of a new Orphanet project as OD4RD (Orphanet Data for Rare Diseases). In this frame we develop a dedicated GitHub space in order to all National hubs teams to connect and share Q/A as well as providing an helpdesk tool they can use nationally. I will answer your issues posted here within RD-CODE and I encourage you to now reach us at: [OD4RD GitHub](https://github.com/OD4RD/Main-Help-Desk/issues) and/or to keep in touch with your National Hub.

Houda previous's answer was complete since both identified genes SLC34A3 and SLC34A1 are linked to ORPHA:157215 and taking into account all types of mutations with their respective transmission mode. Regarding the etiology, after verification the edition team actually evaluated that an abstract was not necessary, and they choose to keep only a short and generic definition, you can see online.

Hope this solves out your question, please let me know if you need more informations on this, 
Kind Regards, 
Marie-Cécile
