### ISSUE TITLE
ORPHA:439167 Placental insufficiency 

### ISSUE THREAD

**Issue by Marlies99** [orphanet-rare-diseases-issues/RD-CODE#9]
Dear All

I have another question concerning ORPHA:439167 Placental insufficiency. When you use thise code for coding, do you code it only for the mother? Or also for the child? I ask because the diagnosis has especially an influence on the child (e.g. small for gestational age). But until now i have mainly thought that it is a maternal diagnosis. 

Thanks for your inputs.
Best regards
Marlies

**Comment by houda-ali** [comment]
Dear Marlies, 
First of all, my apologies for the delayed response to your question. The position in charge of replying to coding-related issues in the GitHub is currently under recruitment, along with other positions in the team and we are having difficulties replying to all requests in an optimal timeframe.
I will come back to you with an answer as soon as possible.
Kind regards,
Houda

**Comment by Marlies99** [comment]
Dear Houda
Do you already know more? About nine months have passed in the meantime...

And another question: Why does this comment not appear in the public comments? Can only i see the question and answer?

Kind Regards
Marlies

**Comment by MCecile-US14** [comment]
Dear @Marlies99,
Very sorry for the late reply, Houda left the team in spring 2022, I am the Nomenclature manager in charge of a new Orphanet project, OD4RD (Orphanet Data for Rare Diseases). In this frame we develop a dedicated GitHub space in order to all National hubs teams to connect and share Q/A as well as providing an helpdesk tool they can use nationally. I will answer your issues posted here within RD-CODE and I encourage you to now reach us at: [OD4RD GitHub](https://github.com/OD4RD/Main-Help-Desk/issues) and/or to keep in touch with your National Hubs

Thank you for your question regarding ORPHA:439167 'Placental insufficiency'. As you know we have several coding recommendations and it seems to me this is part of the main recommendation about usage of ORPHAcodes.
An ORPHAcode is meant to represent a phenotype, not a patient. In this case we consider that the 'Placental insufficiency' is only a maternal condition/consequence (of various risk factors) and in that sense the corresponding ORPHAcode should be used to code only the mother here. Please note that ICD-10/11 also apply same logic since 'Placental insufficiency' is categorized under "maternal care" in their classification. Hence, we do not recommend to use ORPHAcode:439167 to code the baby or child of the mother suffering from placental insufficiency.
[e.g. "Small for gestionnal age" is a non rare condition, also the use ICD-10/11 codes is recommended.]

Hope this clears up your question, 
Kind Regards,
Marie-Cécile
